chore: firebase integration and auth context implementation CU-2wzftem
andreachirico11/domenico-mottola pull request #6
Opened 2022-05-17 18:27 UTC by andreachirico11

2022-05-17 18:27 UTC, andreachirico11 commented
Task linked: [CU-2wzftem setup firebase di sviluppo](https://app.clickup.com/t/2wzftem)

2022-05-17 18:51 UTC, PaoloGiraudi requested changes

2022-05-17 18:51 UTC, PaoloGiraudi commented on styles/globals.css
> +input:disabled {
? Usiamo solo tailwind

2022-05-17 18:55 UTC, PaoloGiraudi requested changes

2022-05-17 18:55 UTC, PaoloGiraudi commented on components/loading-spinner/spinner.tsx
> +  return <>{loading && <p>loading..............</p>}</>
Cerchiamo di farlo un po' più carino. Magari uno spinner? E muoviamo la logica fuori. Nel componente che lo usa fai `isLoading ? <Spinner/> : ...`

2022-05-17 19:10 UTC, PaoloGiraudi requested changes

2022-05-17 19:10 UTC, PaoloGiraudi commented on types/IFIrebaseUser.ts
> +export default interface IFirebaseUser {
Possiamo eliminare la I davanti alle interface? È brutta

2022-05-17 19:10 UTC, PaoloGiraudi commented on types/IFIrebaseUser.ts
> +export default interface IFirebaseUser {
Anche il nome del file è strano

2022-05-18 07:35 UTC, andreachirico11 commented on types/IFIrebaseUser.ts
> +export default interface IFirebaseUser {
Di solito le interfacce ce l'hanno comunque ok

2022-05-18 07:36 UTC, andreachirico11 commented on styles/globals.css
> +input:disabled {
ok

2022-05-18 14:15 UTC, PaoloGiraudi commented on components/loading-spinner/spinner.tsx
> +  return <>{loading && <p>loading..............</p>}</>
Si ma magari il loading dipende da altro. Si cercano di evitare i componenti che "decidono da soli" se fare qualcosa o no. Se non ti piace farlo come ti ho scritto sopra puoi anche fare `if(loading) return <Loader / >`. Ma la logica deve essere fuori dal componente Loader

2022-05-18 18:24 UTC, andreachirico11 commented on components/loading-spinner/spinner.tsx
> +  return <>{loading && <p>loading..............</p>}</>
allora voglio che mi trovi un modo per metterlo a monte tipo dentro _app usando il loading dal context

2022-05-18 18:25 UTC, andreachirico11 commented on types/IFIrebaseUser.ts
> +export default interface IFirebaseUser {
ok come le chiamiamo le interfacce?

2022-05-18 19:28 UTC, PaoloGiraudi commented on components/loading-spinner/spinner.tsx
> +  return <>{loading && <p>loading..............</p>}</>
Si okay basta che lo sposti li ma perche? tanto vale usarlo dove serve, ci sara' piu di un posto no?

2022-05-18 19:29 UTC, PaoloGiraudi commented on types/IFIrebaseUser.ts
> +export default interface IFirebaseUser {
FirebaseUser

2022-05-19 04:14 UTC, andreachirico11 commented on components/loading-spinner/spinner.tsx
> +  return <>{loading && <p>loading..............</p>}</>
di solito i componenti tipo dialog degli errori etc si mettono una volta sola al livello top e si fanno partire da vari punti dell'app senza bisogno di aggiungerli li

2022-05-19 04:17 UTC, PaoloGiraudi commented on components/loading-spinner/spinner.tsx
> +  return <>{loading && <p>loading..............</p>}</>
Ma cosi se hai un componente che sta caricando l'intera app si blocca

2022-05-21 09:38 UTC, PaoloGiraudi approved these changes

2022-05-21 09:38 UTC, merged